name: restaurant_models
description: Restaurant models
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.4

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0


