name: restaurant_ui
description: restaurant ui components
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.4
  flutter: ^3.22.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
