name: restaurant_repository
description: Repository for restaurants
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.4

dependencies:
  restaurant_gql_client:
    path: ../restaurant_gql_client
  restaurant_models:
    path: ../restaurant_models


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
