name: restaurant_gql_client
description: Restaurant gql client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.4

dependencies:
  http: ^1.2.2
  restaurant_models:
    path: ../restaurant_models

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
