name: restaurant_ui

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/restaurant_ui/**"
      - ".github/workflows/restaurant_ui.yaml"
    branches:
      - master

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/restaurant_ui
      min_coverage: 80
